services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=bookstore'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=vazifa2002@'
      - 'MYSQL_USER=root'
    ports:
      - '13306:3306'
