spring:
  liquibase:
    enabled: true
    change-log: classpath:migrations/changelog-master.xml
  datasource:
    username: root
    password: vazifa2002@
    url: jdbc:mysql://localhost:3306/bookstore
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

security:
  jwt:
    public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo3nUG56OuVbsAIwtGXRj9vn6BN3cKxeauZab7ou3iMs6DtonNHCgoduAxwAE+GBXOBNnf1zKv2xsG3sLZEhZ9x0uCoHr4FBMEd8uM9BnMbJkEKEpLwvb/EZT+8avThrWHfwLM/hjiUSWxrw8oWDAlnh0FMYEY05TdDx68SgIMfYBFNluRbLPzmdYFCVrQxfD99C6yNuMPH2/DXTile/m+jJP5WErH9ZE7njYMWlYyhsGHpe0nZeGUZTP9iIHg67b1fdO7k7Nfq+1iunHaFQIwq/nza4qg8pe4bkWnpuLtTCay4y5ZT/fg5d7oPSMXYAx4zXkaJkULpZbe6CnZ0/q1wIDAQAB

    private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCjedQbno65VuwAjC0ZdGP2+foE3dwrF5q5lpvui7eIyzoO2ic0cKCh24DHAAT4YFc4E2d/XMq/bGwbewtkSFn3HS4KgevgUEwR3y4z0GcxsmQQoSkvC9v8RlP7xq9OGtYd/Asz+GOJRJbGvDyhYMCWeHQUxgRjTlN0PHrxKAgx9gEU2W5Fss/OZ1gUJWtDF8P30LrI24w8fb8NdOKV7+b6Mk/lYSsf1kTueNgxaVjKGwYel7Sdl4ZRlM/2IgeDrtvV907uTs1+r7WK6cdoVAjCr+fNriqDyl7huRaem4u1MJrLjLllP9+Dl3ug9IxdgDHjNeRomRQullt7oKdnT+rXAgMBAAECggEAT65qPKwkVSKRFhM9SFL7Br8Bpq2dS0POHvfSOYvQgdTND8A1q9HZ+grL0jOoOIh8+tA6elH4YSWv7BUlkFPTxidq8aQyHLwG2A84rfi+0/Jn49MqB8x4BZciCG7ns+JQy3y22TYRDi9obqYBx4cpWC6OJjH+oYjkFJwGMNWaaP7+3aHDmz/HGgXJbTYyRZNHCaADvwhLjNS2pOSUNRW55Bxhmc4xviJ4cPG0AgFGDPNUfbONRcKFqKSb2XPj7kWDnLpy1umggQz4kYgnLx30BIj8QpkXaBbRvYM0AcxIu5lRabHFpQJbpTlhopNuz+r//nx9068+3iSpkezXZgV+QQKBgQDmh+snBOojvMcOpGWKg+9liOlctcBY8CytrOf2LWq8zGjkxpV0D6jwkG8FBGbPcfpjJEDsnnYDxsBB0QW4k23zzwRW7a9akpawxw8G2/5BLbLyBbPn20KSp7M5WiQPFrANkOcBlYQrZG5OmeOWyG1EBi+VA0TmWskMcQsVUd+4+wKBgQC1iWZJVB5fDkDL0RMp7r+i/nVlpcM3vrDS2tnJAUi3FS56Q+saBIn7rDzyXmXo8yPEPm0BHCzk/kc3SdlVAwbephdS5xIFp1NZBT4/n9ke0ZkhioPkqQ69QPi1irs7rKeOS3u61aGrNqZVAHx23qkEOgP3sF0R9Z/71cS/IbVm1QKBgQCQwGGgc46NeBjJkeKMckGc0LYvV5R6g/yZ5QsV4fi2qednV2Y6pSagPyDm1pezxE7Dd90odmuF/YN1EEl2V2RgBeokp0RHK+pg/+zokrR4urg1De2kNWH88j4wUfB4ZPeQ3R6gOQDvujUlN63XXOx3HSc9evsFZZX+MPETpwBChwKBgFmHXrOxUZ0tiVU7Ukku3sIC3mD4BDP8znXeyuNvx63LO3W/AzZ8oJRHGHOrjHT7XFtPMjEG9TkmEnc4638alAvAO+Z94Qx6vgc8J7v3GHwzgGLjTjK6EXPSlBXsSnSerK/nmCjHbQjkVdm7+KYjH5XfCs/f4baWvYTUo0hj1nPVAoGAPx/dFuPGTY1qpVU1+W+PQADOfy0CFQNa8hv8eRpmaVamwv/ORiOxZTsEmnK5AZLn6GGuc9qwXNj//4ZaQtVxxbD5Rb4VEFczQYr/67lPWIZgxHb+RlwksyAB3LRh8gpc5/jWLcH4tfnG0MpEWHQspmplKRdCp+y0Rdjz1OGkimY=

    access-token-validaty-time: 1800000
    refresh-toke-validaty-time: 8640000



